// Code generated by go-swagger; DO NOT EDIT.

package boarding_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/agentmanagement/v3/models"
)

// GetAgentsIDBoardingConfigurationReader is a Reader for the GetAgentsIDBoardingConfiguration structure.
type GetAgentsIDBoardingConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentsIDBoardingConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentsIDBoardingConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAgentsIDBoardingConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAgentsIDBoardingConfigurationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAgentsIDBoardingConfigurationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAgentsIDBoardingConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetAgentsIDBoardingConfigurationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAgentsIDBoardingConfigurationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetAgentsIDBoardingConfigurationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAgentsIDBoardingConfigurationOK creates a GetAgentsIDBoardingConfigurationOK with default headers values
func NewGetAgentsIDBoardingConfigurationOK() *GetAgentsIDBoardingConfigurationOK {
	return &GetAgentsIDBoardingConfigurationOK{}
}

/*
GetAgentsIDBoardingConfigurationOK describes a response with status code 200, with default header values.

OK
*/
type GetAgentsIDBoardingConfigurationOK struct {
	Payload *models.Configuration
}

// IsSuccess returns true when this get agents Id boarding configuration o k response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get agents Id boarding configuration o k response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration o k response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agents Id boarding configuration o k response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents Id boarding configuration o k response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get agents Id boarding configuration o k response
func (o *GetAgentsIDBoardingConfigurationOK) Code() int {
	return 200
}

func (o *GetAgentsIDBoardingConfigurationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationOK %s", 200, payload)
}

func (o *GetAgentsIDBoardingConfigurationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationOK %s", 200, payload)
}

func (o *GetAgentsIDBoardingConfigurationOK) GetPayload() *models.Configuration {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Configuration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationBadRequest creates a GetAgentsIDBoardingConfigurationBadRequest with default headers values
func NewGetAgentsIDBoardingConfigurationBadRequest() *GetAgentsIDBoardingConfigurationBadRequest {
	return &GetAgentsIDBoardingConfigurationBadRequest{}
}

/*
GetAgentsIDBoardingConfigurationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAgentsIDBoardingConfigurationBadRequest struct {
	Payload *models.Badrequest
}

// IsSuccess returns true when this get agents Id boarding configuration bad request response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents Id boarding configuration bad request response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration bad request response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents Id boarding configuration bad request response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents Id boarding configuration bad request response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get agents Id boarding configuration bad request response
func (o *GetAgentsIDBoardingConfigurationBadRequest) Code() int {
	return 400
}

func (o *GetAgentsIDBoardingConfigurationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationBadRequest %s", 400, payload)
}

func (o *GetAgentsIDBoardingConfigurationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationBadRequest %s", 400, payload)
}

func (o *GetAgentsIDBoardingConfigurationBadRequest) GetPayload() *models.Badrequest {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Badrequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationUnauthorized creates a GetAgentsIDBoardingConfigurationUnauthorized with default headers values
func NewGetAgentsIDBoardingConfigurationUnauthorized() *GetAgentsIDBoardingConfigurationUnauthorized {
	return &GetAgentsIDBoardingConfigurationUnauthorized{}
}

/*
GetAgentsIDBoardingConfigurationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAgentsIDBoardingConfigurationUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this get agents Id boarding configuration unauthorized response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents Id boarding configuration unauthorized response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration unauthorized response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents Id boarding configuration unauthorized response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents Id boarding configuration unauthorized response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get agents Id boarding configuration unauthorized response
func (o *GetAgentsIDBoardingConfigurationUnauthorized) Code() int {
	return 401
}

func (o *GetAgentsIDBoardingConfigurationUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationUnauthorized %s", 401, payload)
}

func (o *GetAgentsIDBoardingConfigurationUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationUnauthorized %s", 401, payload)
}

func (o *GetAgentsIDBoardingConfigurationUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationForbidden creates a GetAgentsIDBoardingConfigurationForbidden with default headers values
func NewGetAgentsIDBoardingConfigurationForbidden() *GetAgentsIDBoardingConfigurationForbidden {
	return &GetAgentsIDBoardingConfigurationForbidden{}
}

/*
GetAgentsIDBoardingConfigurationForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAgentsIDBoardingConfigurationForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this get agents Id boarding configuration forbidden response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents Id boarding configuration forbidden response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration forbidden response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents Id boarding configuration forbidden response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents Id boarding configuration forbidden response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get agents Id boarding configuration forbidden response
func (o *GetAgentsIDBoardingConfigurationForbidden) Code() int {
	return 403
}

func (o *GetAgentsIDBoardingConfigurationForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationForbidden %s", 403, payload)
}

func (o *GetAgentsIDBoardingConfigurationForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationForbidden %s", 403, payload)
}

func (o *GetAgentsIDBoardingConfigurationForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationNotFound creates a GetAgentsIDBoardingConfigurationNotFound with default headers values
func NewGetAgentsIDBoardingConfigurationNotFound() *GetAgentsIDBoardingConfigurationNotFound {
	return &GetAgentsIDBoardingConfigurationNotFound{}
}

/*
GetAgentsIDBoardingConfigurationNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAgentsIDBoardingConfigurationNotFound struct {
	Payload *models.Notfound
}

// IsSuccess returns true when this get agents Id boarding configuration not found response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents Id boarding configuration not found response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration not found response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents Id boarding configuration not found response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents Id boarding configuration not found response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get agents Id boarding configuration not found response
func (o *GetAgentsIDBoardingConfigurationNotFound) Code() int {
	return 404
}

func (o *GetAgentsIDBoardingConfigurationNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationNotFound %s", 404, payload)
}

func (o *GetAgentsIDBoardingConfigurationNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationNotFound %s", 404, payload)
}

func (o *GetAgentsIDBoardingConfigurationNotFound) GetPayload() *models.Notfound {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Notfound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationTooManyRequests creates a GetAgentsIDBoardingConfigurationTooManyRequests with default headers values
func NewGetAgentsIDBoardingConfigurationTooManyRequests() *GetAgentsIDBoardingConfigurationTooManyRequests {
	return &GetAgentsIDBoardingConfigurationTooManyRequests{}
}

/*
GetAgentsIDBoardingConfigurationTooManyRequests describes a response with status code 429, with default header values.

API rate limit exceeded.
*/
type GetAgentsIDBoardingConfigurationTooManyRequests struct {
	Payload *models.APIRateLimitExceeded
}

// IsSuccess returns true when this get agents Id boarding configuration too many requests response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents Id boarding configuration too many requests response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration too many requests response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents Id boarding configuration too many requests response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents Id boarding configuration too many requests response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get agents Id boarding configuration too many requests response
func (o *GetAgentsIDBoardingConfigurationTooManyRequests) Code() int {
	return 429
}

func (o *GetAgentsIDBoardingConfigurationTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationTooManyRequests %s", 429, payload)
}

func (o *GetAgentsIDBoardingConfigurationTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationTooManyRequests %s", 429, payload)
}

func (o *GetAgentsIDBoardingConfigurationTooManyRequests) GetPayload() *models.APIRateLimitExceeded {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRateLimitExceeded)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationInternalServerError creates a GetAgentsIDBoardingConfigurationInternalServerError with default headers values
func NewGetAgentsIDBoardingConfigurationInternalServerError() *GetAgentsIDBoardingConfigurationInternalServerError {
	return &GetAgentsIDBoardingConfigurationInternalServerError{}
}

/*
GetAgentsIDBoardingConfigurationInternalServerError describes a response with status code 500, with default header values.

unexpected error
*/
type GetAgentsIDBoardingConfigurationInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get agents Id boarding configuration internal server error response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents Id boarding configuration internal server error response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents Id boarding configuration internal server error response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agents Id boarding configuration internal server error response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get agents Id boarding configuration internal server error response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get agents Id boarding configuration internal server error response
func (o *GetAgentsIDBoardingConfigurationInternalServerError) Code() int {
	return 500
}

func (o *GetAgentsIDBoardingConfigurationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationInternalServerError %s", 500, payload)
}

func (o *GetAgentsIDBoardingConfigurationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] getAgentsIdBoardingConfigurationInternalServerError %s", 500, payload)
}

func (o *GetAgentsIDBoardingConfigurationInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentsIDBoardingConfigurationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsIDBoardingConfigurationDefault creates a GetAgentsIDBoardingConfigurationDefault with default headers values
func NewGetAgentsIDBoardingConfigurationDefault(code int) *GetAgentsIDBoardingConfigurationDefault {
	return &GetAgentsIDBoardingConfigurationDefault{
		_statusCode: code,
	}
}

/*
GetAgentsIDBoardingConfigurationDefault describes a response with status code -1, with default header values.

Other error with any status code and response body format.
*/
type GetAgentsIDBoardingConfigurationDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get agents ID boarding configuration default response has a 2xx status code
func (o *GetAgentsIDBoardingConfigurationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get agents ID boarding configuration default response has a 3xx status code
func (o *GetAgentsIDBoardingConfigurationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get agents ID boarding configuration default response has a 4xx status code
func (o *GetAgentsIDBoardingConfigurationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get agents ID boarding configuration default response has a 5xx status code
func (o *GetAgentsIDBoardingConfigurationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get agents ID boarding configuration default response a status code equal to that given
func (o *GetAgentsIDBoardingConfigurationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get agents ID boarding configuration default response
func (o *GetAgentsIDBoardingConfigurationDefault) Code() int {
	return o._statusCode
}

func (o *GetAgentsIDBoardingConfigurationDefault) Error() string {
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] GetAgentsIDBoardingConfiguration default", o._statusCode)
}

func (o *GetAgentsIDBoardingConfigurationDefault) String() string {
	return fmt.Sprintf("[GET /agents/{id}/boarding/configuration][%d] GetAgentsIDBoardingConfiguration default", o._statusCode)
}

func (o *GetAgentsIDBoardingConfigurationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
