// Code generated by go-swagger; DO NOT EDIT.

package boarding_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAgentsIDBoardingStatusParams creates a new GetAgentsIDBoardingStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAgentsIDBoardingStatusParams() *GetAgentsIDBoardingStatusParams {
	return &GetAgentsIDBoardingStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAgentsIDBoardingStatusParamsWithTimeout creates a new GetAgentsIDBoardingStatusParams object
// with the ability to set a timeout on a request.
func NewGetAgentsIDBoardingStatusParamsWithTimeout(timeout time.Duration) *GetAgentsIDBoardingStatusParams {
	return &GetAgentsIDBoardingStatusParams{
		timeout: timeout,
	}
}

// NewGetAgentsIDBoardingStatusParamsWithContext creates a new GetAgentsIDBoardingStatusParams object
// with the ability to set a context for a request.
func NewGetAgentsIDBoardingStatusParamsWithContext(ctx context.Context) *GetAgentsIDBoardingStatusParams {
	return &GetAgentsIDBoardingStatusParams{
		Context: ctx,
	}
}

// NewGetAgentsIDBoardingStatusParamsWithHTTPClient creates a new GetAgentsIDBoardingStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAgentsIDBoardingStatusParamsWithHTTPClient(client *http.Client) *GetAgentsIDBoardingStatusParams {
	return &GetAgentsIDBoardingStatusParams{
		HTTPClient: client,
	}
}

/*
GetAgentsIDBoardingStatusParams contains all the parameters to send to the API endpoint

	for the get agents ID boarding status operation.

	Typically these are written to a http.Request.
*/
type GetAgentsIDBoardingStatusParams struct {

	/* ID.

	   Unique identifier of the agent.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get agents ID boarding status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAgentsIDBoardingStatusParams) WithDefaults() *GetAgentsIDBoardingStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get agents ID boarding status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAgentsIDBoardingStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) WithTimeout(timeout time.Duration) *GetAgentsIDBoardingStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) WithContext(ctx context.Context) *GetAgentsIDBoardingStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) WithHTTPClient(client *http.Client) *GetAgentsIDBoardingStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) WithID(id string) *GetAgentsIDBoardingStatusParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get agents ID boarding status params
func (o *GetAgentsIDBoardingStatusParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAgentsIDBoardingStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
