// Code generated by go-swagger; DO NOT EDIT.

package boarding_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAgentsIDBoardingOffboardParams creates a new PostAgentsIDBoardingOffboardParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAgentsIDBoardingOffboardParams() *PostAgentsIDBoardingOffboardParams {
	return &PostAgentsIDBoardingOffboardParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAgentsIDBoardingOffboardParamsWithTimeout creates a new PostAgentsIDBoardingOffboardParams object
// with the ability to set a timeout on a request.
func NewPostAgentsIDBoardingOffboardParamsWithTimeout(timeout time.Duration) *PostAgentsIDBoardingOffboardParams {
	return &PostAgentsIDBoardingOffboardParams{
		timeout: timeout,
	}
}

// NewPostAgentsIDBoardingOffboardParamsWithContext creates a new PostAgentsIDBoardingOffboardParams object
// with the ability to set a context for a request.
func NewPostAgentsIDBoardingOffboardParamsWithContext(ctx context.Context) *PostAgentsIDBoardingOffboardParams {
	return &PostAgentsIDBoardingOffboardParams{
		Context: ctx,
	}
}

// NewPostAgentsIDBoardingOffboardParamsWithHTTPClient creates a new PostAgentsIDBoardingOffboardParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAgentsIDBoardingOffboardParamsWithHTTPClient(client *http.Client) *PostAgentsIDBoardingOffboardParams {
	return &PostAgentsIDBoardingOffboardParams{
		HTTPClient: client,
	}
}

/*
PostAgentsIDBoardingOffboardParams contains all the parameters to send to the API endpoint

	for the post agents ID boarding offboard operation.

	Typically these are written to a http.Request.
*/
type PostAgentsIDBoardingOffboardParams struct {

	/* ID.

	   Unique identifier of the agent.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post agents ID boarding offboard params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAgentsIDBoardingOffboardParams) WithDefaults() *PostAgentsIDBoardingOffboardParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post agents ID boarding offboard params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAgentsIDBoardingOffboardParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) WithTimeout(timeout time.Duration) *PostAgentsIDBoardingOffboardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) WithContext(ctx context.Context) *PostAgentsIDBoardingOffboardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) WithHTTPClient(client *http.Client) *PostAgentsIDBoardingOffboardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) WithID(id string) *PostAgentsIDBoardingOffboardParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post agents ID boarding offboard params
func (o *PostAgentsIDBoardingOffboardParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostAgentsIDBoardingOffboardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
