// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/client/diagnostic_activations"
	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/client/diagnostic_information"
	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/client/event_mappings"
	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/client/exchange"
	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/client/mappings"
	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/client/record_recovery"
)

// Default mind connect API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/mindconnect/v3"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new mind connect API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *MindConnectAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new mind connect API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *MindConnectAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new mind connect API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *MindConnectAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(MindConnectAPI)
	cli.Transport = transport
	cli.DiagnosticActivations = diagnostic_activations.New(transport, formats)
	cli.DiagnosticInformation = diagnostic_information.New(transport, formats)
	cli.EventMappings = event_mappings.New(transport, formats)
	cli.Exchange = exchange.New(transport, formats)
	cli.Mappings = mappings.New(transport, formats)
	cli.RecordRecovery = record_recovery.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// MindConnectAPI is a client for mind connect API
type MindConnectAPI struct {
	DiagnosticActivations diagnostic_activations.ClientService

	DiagnosticInformation diagnostic_information.ClientService

	EventMappings event_mappings.ClientService

	Exchange exchange.ClientService

	Mappings mappings.ClientService

	RecordRecovery record_recovery.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *MindConnectAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.DiagnosticActivations.SetTransport(transport)
	c.DiagnosticInformation.SetTransport(transport)
	c.EventMappings.SetTransport(transport)
	c.Exchange.SetTransport(transport)
	c.Mappings.SetTransport(transport)
	c.RecordRecovery.SetTransport(transport)
}
