// Code generated by go-swagger; DO NOT EDIT.

package aspecttype

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/calacaly/mindconnect-go/internal/api/assetmanagement/v3/models"
)

// NewSaveAspectTypeParams creates a new SaveAspectTypeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSaveAspectTypeParams() *SaveAspectTypeParams {
	return &SaveAspectTypeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSaveAspectTypeParamsWithTimeout creates a new SaveAspectTypeParams object
// with the ability to set a timeout on a request.
func NewSaveAspectTypeParamsWithTimeout(timeout time.Duration) *SaveAspectTypeParams {
	return &SaveAspectTypeParams{
		timeout: timeout,
	}
}

// NewSaveAspectTypeParamsWithContext creates a new SaveAspectTypeParams object
// with the ability to set a context for a request.
func NewSaveAspectTypeParamsWithContext(ctx context.Context) *SaveAspectTypeParams {
	return &SaveAspectTypeParams{
		Context: ctx,
	}
}

// NewSaveAspectTypeParamsWithHTTPClient creates a new SaveAspectTypeParams object
// with the ability to set a custom HTTPClient for a request.
func NewSaveAspectTypeParamsWithHTTPClient(client *http.Client) *SaveAspectTypeParams {
	return &SaveAspectTypeParams{
		HTTPClient: client,
	}
}

/*
SaveAspectTypeParams contains all the parameters to send to the API endpoint

	for the save aspect type operation.

	Typically these are written to a http.Request.
*/
type SaveAspectTypeParams struct {

	/* IfMatch.

	     Last known version to facilitate optimistic locking.
	*Required for modification.

	*/
	IfMatch *string

	/* IfNoneMatch.

	   Set ifNoneMatch header to "*" for ensuring create request
	*/
	IfNoneMatch *string

	/* Aspecttype.

	   aspect type
	*/
	Aspecttype *models.AspectType

	/* ID.

	   The type's id is a unique identifier. The id's length must be between 1 and 128 characters and matches the following symbols "A-Z", "a-z", "0-9", "_" and "." beginning with the tenant prefix what has a maximum of 8 characters. (e.g . ten_pref.type_id)
	*/
	ID string

	/* IncludeShared.

	   Specifies if the operation should take into account shared (received) assets, aspects and asset types. Received resources are not visible in case includeShared=false. For query operations, received resources are not returned. Endpoints addressing individual resources respond with 404. In case received resources are referenced in a request parameter or property, they are treated as not existing.
	*/
	IncludeShared *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the save aspect type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveAspectTypeParams) WithDefaults() *SaveAspectTypeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the save aspect type params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SaveAspectTypeParams) SetDefaults() {
	var (
		includeSharedDefault = bool(false)
	)

	val := SaveAspectTypeParams{
		IncludeShared: &includeSharedDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the save aspect type params
func (o *SaveAspectTypeParams) WithTimeout(timeout time.Duration) *SaveAspectTypeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save aspect type params
func (o *SaveAspectTypeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save aspect type params
func (o *SaveAspectTypeParams) WithContext(ctx context.Context) *SaveAspectTypeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save aspect type params
func (o *SaveAspectTypeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save aspect type params
func (o *SaveAspectTypeParams) WithHTTPClient(client *http.Client) *SaveAspectTypeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save aspect type params
func (o *SaveAspectTypeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIfMatch adds the ifMatch to the save aspect type params
func (o *SaveAspectTypeParams) WithIfMatch(ifMatch *string) *SaveAspectTypeParams {
	o.SetIfMatch(ifMatch)
	return o
}

// SetIfMatch adds the ifMatch to the save aspect type params
func (o *SaveAspectTypeParams) SetIfMatch(ifMatch *string) {
	o.IfMatch = ifMatch
}

// WithIfNoneMatch adds the ifNoneMatch to the save aspect type params
func (o *SaveAspectTypeParams) WithIfNoneMatch(ifNoneMatch *string) *SaveAspectTypeParams {
	o.SetIfNoneMatch(ifNoneMatch)
	return o
}

// SetIfNoneMatch adds the ifNoneMatch to the save aspect type params
func (o *SaveAspectTypeParams) SetIfNoneMatch(ifNoneMatch *string) {
	o.IfNoneMatch = ifNoneMatch
}

// WithAspecttype adds the aspecttype to the save aspect type params
func (o *SaveAspectTypeParams) WithAspecttype(aspecttype *models.AspectType) *SaveAspectTypeParams {
	o.SetAspecttype(aspecttype)
	return o
}

// SetAspecttype adds the aspecttype to the save aspect type params
func (o *SaveAspectTypeParams) SetAspecttype(aspecttype *models.AspectType) {
	o.Aspecttype = aspecttype
}

// WithID adds the id to the save aspect type params
func (o *SaveAspectTypeParams) WithID(id string) *SaveAspectTypeParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the save aspect type params
func (o *SaveAspectTypeParams) SetID(id string) {
	o.ID = id
}

// WithIncludeShared adds the includeShared to the save aspect type params
func (o *SaveAspectTypeParams) WithIncludeShared(includeShared *bool) *SaveAspectTypeParams {
	o.SetIncludeShared(includeShared)
	return o
}

// SetIncludeShared adds the includeShared to the save aspect type params
func (o *SaveAspectTypeParams) SetIncludeShared(includeShared *bool) {
	o.IncludeShared = includeShared
}

// WriteToRequest writes these params to a swagger request
func (o *SaveAspectTypeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IfMatch != nil {

		// header param If-Match
		if err := r.SetHeaderParam("If-Match", *o.IfMatch); err != nil {
			return err
		}
	}

	if o.IfNoneMatch != nil {

		// header param If-None-Match
		if err := r.SetHeaderParam("If-None-Match", *o.IfNoneMatch); err != nil {
			return err
		}
	}
	if o.Aspecttype != nil {
		if err := r.SetBodyParam(o.Aspecttype); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.IncludeShared != nil {

		// query param includeShared
		var qrIncludeShared bool

		if o.IncludeShared != nil {
			qrIncludeShared = *o.IncludeShared
		}
		qIncludeShared := swag.FormatBool(qrIncludeShared)
		if qIncludeShared != "" {

			if err := r.SetQueryParam("includeShared", qIncludeShared); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
