// Code generated by go-swagger; DO NOT EDIT.

package record_recovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteRecoverableRecordsIDParams creates a new DeleteRecoverableRecordsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteRecoverableRecordsIDParams() *DeleteRecoverableRecordsIDParams {
	return &DeleteRecoverableRecordsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRecoverableRecordsIDParamsWithTimeout creates a new DeleteRecoverableRecordsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteRecoverableRecordsIDParamsWithTimeout(timeout time.Duration) *DeleteRecoverableRecordsIDParams {
	return &DeleteRecoverableRecordsIDParams{
		timeout: timeout,
	}
}

// NewDeleteRecoverableRecordsIDParamsWithContext creates a new DeleteRecoverableRecordsIDParams object
// with the ability to set a context for a request.
func NewDeleteRecoverableRecordsIDParamsWithContext(ctx context.Context) *DeleteRecoverableRecordsIDParams {
	return &DeleteRecoverableRecordsIDParams{
		Context: ctx,
	}
}

// NewDeleteRecoverableRecordsIDParamsWithHTTPClient creates a new DeleteRecoverableRecordsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteRecoverableRecordsIDParamsWithHTTPClient(client *http.Client) *DeleteRecoverableRecordsIDParams {
	return &DeleteRecoverableRecordsIDParams{
		HTTPClient: client,
	}
}

/*
DeleteRecoverableRecordsIDParams contains all the parameters to send to the API endpoint

	for the delete recoverable records ID operation.

	Typically these are written to a http.Request.
*/
type DeleteRecoverableRecordsIDParams struct {

	/* ID.

	   Unique identifier of the recoverable record.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete recoverable records ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRecoverableRecordsIDParams) WithDefaults() *DeleteRecoverableRecordsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete recoverable records ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRecoverableRecordsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) WithTimeout(timeout time.Duration) *DeleteRecoverableRecordsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) WithContext(ctx context.Context) *DeleteRecoverableRecordsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) WithHTTPClient(client *http.Client) *DeleteRecoverableRecordsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) WithID(id string) *DeleteRecoverableRecordsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete recoverable records ID params
func (o *DeleteRecoverableRecordsIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRecoverableRecordsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
