// Code generated by go-swagger; DO NOT EDIT.

package data_source_configuration_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/agentmanagement/v3/models"
)

// PutAgentsIDDataSourceConfigurationReader is a Reader for the PutAgentsIDDataSourceConfiguration structure.
type PutAgentsIDDataSourceConfigurationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAgentsIDDataSourceConfigurationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAgentsIDDataSourceConfigurationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPutAgentsIDDataSourceConfigurationBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPutAgentsIDDataSourceConfigurationUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewPutAgentsIDDataSourceConfigurationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPutAgentsIDDataSourceConfigurationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewPutAgentsIDDataSourceConfigurationPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewPutAgentsIDDataSourceConfigurationTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPutAgentsIDDataSourceConfigurationInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPutAgentsIDDataSourceConfigurationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutAgentsIDDataSourceConfigurationOK creates a PutAgentsIDDataSourceConfigurationOK with default headers values
func NewPutAgentsIDDataSourceConfigurationOK() *PutAgentsIDDataSourceConfigurationOK {
	return &PutAgentsIDDataSourceConfigurationOK{}
}

/*
PutAgentsIDDataSourceConfigurationOK describes a response with status code 200, with default header values.

OK
*/
type PutAgentsIDDataSourceConfigurationOK struct {
	Payload *models.DataSourceConfiguration
}

// IsSuccess returns true when this put agents Id data source configuration o k response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put agents Id data source configuration o k response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration o k response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put agents Id data source configuration o k response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration o k response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put agents Id data source configuration o k response
func (o *PutAgentsIDDataSourceConfigurationOK) Code() int {
	return 200
}

func (o *PutAgentsIDDataSourceConfigurationOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationOK %s", 200, payload)
}

func (o *PutAgentsIDDataSourceConfigurationOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationOK %s", 200, payload)
}

func (o *PutAgentsIDDataSourceConfigurationOK) GetPayload() *models.DataSourceConfiguration {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DataSourceConfiguration)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationBadRequest creates a PutAgentsIDDataSourceConfigurationBadRequest with default headers values
func NewPutAgentsIDDataSourceConfigurationBadRequest() *PutAgentsIDDataSourceConfigurationBadRequest {
	return &PutAgentsIDDataSourceConfigurationBadRequest{}
}

/*
PutAgentsIDDataSourceConfigurationBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PutAgentsIDDataSourceConfigurationBadRequest struct {
	Payload *models.Badrequest
}

// IsSuccess returns true when this put agents Id data source configuration bad request response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration bad request response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration bad request response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this put agents Id data source configuration bad request response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration bad request response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the put agents Id data source configuration bad request response
func (o *PutAgentsIDDataSourceConfigurationBadRequest) Code() int {
	return 400
}

func (o *PutAgentsIDDataSourceConfigurationBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationBadRequest %s", 400, payload)
}

func (o *PutAgentsIDDataSourceConfigurationBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationBadRequest %s", 400, payload)
}

func (o *PutAgentsIDDataSourceConfigurationBadRequest) GetPayload() *models.Badrequest {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Badrequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationUnauthorized creates a PutAgentsIDDataSourceConfigurationUnauthorized with default headers values
func NewPutAgentsIDDataSourceConfigurationUnauthorized() *PutAgentsIDDataSourceConfigurationUnauthorized {
	return &PutAgentsIDDataSourceConfigurationUnauthorized{}
}

/*
PutAgentsIDDataSourceConfigurationUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PutAgentsIDDataSourceConfigurationUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this put agents Id data source configuration unauthorized response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration unauthorized response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration unauthorized response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this put agents Id data source configuration unauthorized response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration unauthorized response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the put agents Id data source configuration unauthorized response
func (o *PutAgentsIDDataSourceConfigurationUnauthorized) Code() int {
	return 401
}

func (o *PutAgentsIDDataSourceConfigurationUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationUnauthorized %s", 401, payload)
}

func (o *PutAgentsIDDataSourceConfigurationUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationUnauthorized %s", 401, payload)
}

func (o *PutAgentsIDDataSourceConfigurationUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationForbidden creates a PutAgentsIDDataSourceConfigurationForbidden with default headers values
func NewPutAgentsIDDataSourceConfigurationForbidden() *PutAgentsIDDataSourceConfigurationForbidden {
	return &PutAgentsIDDataSourceConfigurationForbidden{}
}

/*
PutAgentsIDDataSourceConfigurationForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type PutAgentsIDDataSourceConfigurationForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this put agents Id data source configuration forbidden response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration forbidden response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration forbidden response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this put agents Id data source configuration forbidden response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration forbidden response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the put agents Id data source configuration forbidden response
func (o *PutAgentsIDDataSourceConfigurationForbidden) Code() int {
	return 403
}

func (o *PutAgentsIDDataSourceConfigurationForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationForbidden %s", 403, payload)
}

func (o *PutAgentsIDDataSourceConfigurationForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationForbidden %s", 403, payload)
}

func (o *PutAgentsIDDataSourceConfigurationForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationNotFound creates a PutAgentsIDDataSourceConfigurationNotFound with default headers values
func NewPutAgentsIDDataSourceConfigurationNotFound() *PutAgentsIDDataSourceConfigurationNotFound {
	return &PutAgentsIDDataSourceConfigurationNotFound{}
}

/*
PutAgentsIDDataSourceConfigurationNotFound describes a response with status code 404, with default header values.

Not Found
*/
type PutAgentsIDDataSourceConfigurationNotFound struct {
	Payload *models.Notfound
}

// IsSuccess returns true when this put agents Id data source configuration not found response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration not found response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration not found response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this put agents Id data source configuration not found response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration not found response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the put agents Id data source configuration not found response
func (o *PutAgentsIDDataSourceConfigurationNotFound) Code() int {
	return 404
}

func (o *PutAgentsIDDataSourceConfigurationNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationNotFound %s", 404, payload)
}

func (o *PutAgentsIDDataSourceConfigurationNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationNotFound %s", 404, payload)
}

func (o *PutAgentsIDDataSourceConfigurationNotFound) GetPayload() *models.Notfound {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Notfound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationPreconditionFailed creates a PutAgentsIDDataSourceConfigurationPreconditionFailed with default headers values
func NewPutAgentsIDDataSourceConfigurationPreconditionFailed() *PutAgentsIDDataSourceConfigurationPreconditionFailed {
	return &PutAgentsIDDataSourceConfigurationPreconditionFailed{}
}

/*
PutAgentsIDDataSourceConfigurationPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type PutAgentsIDDataSourceConfigurationPreconditionFailed struct {
	Payload *models.Preconditionfailed
}

// IsSuccess returns true when this put agents Id data source configuration precondition failed response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration precondition failed response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration precondition failed response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this put agents Id data source configuration precondition failed response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration precondition failed response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the put agents Id data source configuration precondition failed response
func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) Code() int {
	return 412
}

func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationPreconditionFailed %s", 412, payload)
}

func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationPreconditionFailed %s", 412, payload)
}

func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) GetPayload() *models.Preconditionfailed {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Preconditionfailed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationTooManyRequests creates a PutAgentsIDDataSourceConfigurationTooManyRequests with default headers values
func NewPutAgentsIDDataSourceConfigurationTooManyRequests() *PutAgentsIDDataSourceConfigurationTooManyRequests {
	return &PutAgentsIDDataSourceConfigurationTooManyRequests{}
}

/*
PutAgentsIDDataSourceConfigurationTooManyRequests describes a response with status code 429, with default header values.

API rate limit exceeded.
*/
type PutAgentsIDDataSourceConfigurationTooManyRequests struct {
	Payload *models.APIRateLimitExceeded
}

// IsSuccess returns true when this put agents Id data source configuration too many requests response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration too many requests response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration too many requests response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this put agents Id data source configuration too many requests response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this put agents Id data source configuration too many requests response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the put agents Id data source configuration too many requests response
func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) Code() int {
	return 429
}

func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationTooManyRequests %s", 429, payload)
}

func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationTooManyRequests %s", 429, payload)
}

func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) GetPayload() *models.APIRateLimitExceeded {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRateLimitExceeded)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationInternalServerError creates a PutAgentsIDDataSourceConfigurationInternalServerError with default headers values
func NewPutAgentsIDDataSourceConfigurationInternalServerError() *PutAgentsIDDataSourceConfigurationInternalServerError {
	return &PutAgentsIDDataSourceConfigurationInternalServerError{}
}

/*
PutAgentsIDDataSourceConfigurationInternalServerError describes a response with status code 500, with default header values.

unexpected error
*/
type PutAgentsIDDataSourceConfigurationInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this put agents Id data source configuration internal server error response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put agents Id data source configuration internal server error response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put agents Id data source configuration internal server error response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put agents Id data source configuration internal server error response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put agents Id data source configuration internal server error response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put agents Id data source configuration internal server error response
func (o *PutAgentsIDDataSourceConfigurationInternalServerError) Code() int {
	return 500
}

func (o *PutAgentsIDDataSourceConfigurationInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationInternalServerError %s", 500, payload)
}

func (o *PutAgentsIDDataSourceConfigurationInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] putAgentsIdDataSourceConfigurationInternalServerError %s", 500, payload)
}

func (o *PutAgentsIDDataSourceConfigurationInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PutAgentsIDDataSourceConfigurationInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutAgentsIDDataSourceConfigurationDefault creates a PutAgentsIDDataSourceConfigurationDefault with default headers values
func NewPutAgentsIDDataSourceConfigurationDefault(code int) *PutAgentsIDDataSourceConfigurationDefault {
	return &PutAgentsIDDataSourceConfigurationDefault{
		_statusCode: code,
	}
}

/*
PutAgentsIDDataSourceConfigurationDefault describes a response with status code -1, with default header values.

Other error with any status code and response body format.
*/
type PutAgentsIDDataSourceConfigurationDefault struct {
	_statusCode int
}

// IsSuccess returns true when this put agents ID data source configuration default response has a 2xx status code
func (o *PutAgentsIDDataSourceConfigurationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this put agents ID data source configuration default response has a 3xx status code
func (o *PutAgentsIDDataSourceConfigurationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this put agents ID data source configuration default response has a 4xx status code
func (o *PutAgentsIDDataSourceConfigurationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this put agents ID data source configuration default response has a 5xx status code
func (o *PutAgentsIDDataSourceConfigurationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this put agents ID data source configuration default response a status code equal to that given
func (o *PutAgentsIDDataSourceConfigurationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the put agents ID data source configuration default response
func (o *PutAgentsIDDataSourceConfigurationDefault) Code() int {
	return o._statusCode
}

func (o *PutAgentsIDDataSourceConfigurationDefault) Error() string {
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] PutAgentsIDDataSourceConfiguration default", o._statusCode)
}

func (o *PutAgentsIDDataSourceConfigurationDefault) String() string {
	return fmt.Sprintf("[PUT /agents/{id}/dataSourceConfiguration][%d] PutAgentsIDDataSourceConfiguration default", o._statusCode)
}

func (o *PutAgentsIDDataSourceConfigurationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
