// Code generated by go-swagger; DO NOT EDIT.

package mappings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/models"
)

// GetDataPointMappingsReader is a Reader for the GetDataPointMappings structure.
type GetDataPointMappingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDataPointMappingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDataPointMappingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDataPointMappingsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetDataPointMappingsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDataPointMappingsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetDataPointMappingsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetDataPointMappingsOK creates a GetDataPointMappingsOK with default headers values
func NewGetDataPointMappingsOK() *GetDataPointMappingsOK {
	return &GetDataPointMappingsOK{}
}

/*
GetDataPointMappingsOK describes a response with status code 200, with default header values.

OK
*/
type GetDataPointMappingsOK struct {
	Payload *models.PagedMapping
}

// IsSuccess returns true when this get data point mappings o k response has a 2xx status code
func (o *GetDataPointMappingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get data point mappings o k response has a 3xx status code
func (o *GetDataPointMappingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data point mappings o k response has a 4xx status code
func (o *GetDataPointMappingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get data point mappings o k response has a 5xx status code
func (o *GetDataPointMappingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get data point mappings o k response a status code equal to that given
func (o *GetDataPointMappingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get data point mappings o k response
func (o *GetDataPointMappingsOK) Code() int {
	return 200
}

func (o *GetDataPointMappingsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsOK %s", 200, payload)
}

func (o *GetDataPointMappingsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsOK %s", 200, payload)
}

func (o *GetDataPointMappingsOK) GetPayload() *models.PagedMapping {
	return o.Payload
}

func (o *GetDataPointMappingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedMapping)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataPointMappingsBadRequest creates a GetDataPointMappingsBadRequest with default headers values
func NewGetDataPointMappingsBadRequest() *GetDataPointMappingsBadRequest {
	return &GetDataPointMappingsBadRequest{}
}

/*
GetDataPointMappingsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetDataPointMappingsBadRequest struct {
	Payload *models.Badrequest
}

// IsSuccess returns true when this get data point mappings bad request response has a 2xx status code
func (o *GetDataPointMappingsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data point mappings bad request response has a 3xx status code
func (o *GetDataPointMappingsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data point mappings bad request response has a 4xx status code
func (o *GetDataPointMappingsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get data point mappings bad request response has a 5xx status code
func (o *GetDataPointMappingsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get data point mappings bad request response a status code equal to that given
func (o *GetDataPointMappingsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get data point mappings bad request response
func (o *GetDataPointMappingsBadRequest) Code() int {
	return 400
}

func (o *GetDataPointMappingsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsBadRequest %s", 400, payload)
}

func (o *GetDataPointMappingsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsBadRequest %s", 400, payload)
}

func (o *GetDataPointMappingsBadRequest) GetPayload() *models.Badrequest {
	return o.Payload
}

func (o *GetDataPointMappingsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Badrequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataPointMappingsUnauthorized creates a GetDataPointMappingsUnauthorized with default headers values
func NewGetDataPointMappingsUnauthorized() *GetDataPointMappingsUnauthorized {
	return &GetDataPointMappingsUnauthorized{}
}

/*
GetDataPointMappingsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetDataPointMappingsUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this get data point mappings unauthorized response has a 2xx status code
func (o *GetDataPointMappingsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data point mappings unauthorized response has a 3xx status code
func (o *GetDataPointMappingsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data point mappings unauthorized response has a 4xx status code
func (o *GetDataPointMappingsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get data point mappings unauthorized response has a 5xx status code
func (o *GetDataPointMappingsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get data point mappings unauthorized response a status code equal to that given
func (o *GetDataPointMappingsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get data point mappings unauthorized response
func (o *GetDataPointMappingsUnauthorized) Code() int {
	return 401
}

func (o *GetDataPointMappingsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsUnauthorized %s", 401, payload)
}

func (o *GetDataPointMappingsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsUnauthorized %s", 401, payload)
}

func (o *GetDataPointMappingsUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *GetDataPointMappingsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataPointMappingsForbidden creates a GetDataPointMappingsForbidden with default headers values
func NewGetDataPointMappingsForbidden() *GetDataPointMappingsForbidden {
	return &GetDataPointMappingsForbidden{}
}

/*
GetDataPointMappingsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetDataPointMappingsForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this get data point mappings forbidden response has a 2xx status code
func (o *GetDataPointMappingsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get data point mappings forbidden response has a 3xx status code
func (o *GetDataPointMappingsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get data point mappings forbidden response has a 4xx status code
func (o *GetDataPointMappingsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get data point mappings forbidden response has a 5xx status code
func (o *GetDataPointMappingsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get data point mappings forbidden response a status code equal to that given
func (o *GetDataPointMappingsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get data point mappings forbidden response
func (o *GetDataPointMappingsForbidden) Code() int {
	return 403
}

func (o *GetDataPointMappingsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsForbidden %s", 403, payload)
}

func (o *GetDataPointMappingsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] getDataPointMappingsForbidden %s", 403, payload)
}

func (o *GetDataPointMappingsForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *GetDataPointMappingsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDataPointMappingsDefault creates a GetDataPointMappingsDefault with default headers values
func NewGetDataPointMappingsDefault(code int) *GetDataPointMappingsDefault {
	return &GetDataPointMappingsDefault{
		_statusCode: code,
	}
}

/*
GetDataPointMappingsDefault describes a response with status code -1, with default header values.

unexpected error
*/
type GetDataPointMappingsDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this get data point mappings default response has a 2xx status code
func (o *GetDataPointMappingsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get data point mappings default response has a 3xx status code
func (o *GetDataPointMappingsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get data point mappings default response has a 4xx status code
func (o *GetDataPointMappingsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get data point mappings default response has a 5xx status code
func (o *GetDataPointMappingsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get data point mappings default response a status code equal to that given
func (o *GetDataPointMappingsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get data point mappings default response
func (o *GetDataPointMappingsDefault) Code() int {
	return o._statusCode
}

func (o *GetDataPointMappingsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] GetDataPointMappings default %s", o._statusCode, payload)
}

func (o *GetDataPointMappingsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /dataPointMappings][%d] GetDataPointMappings default %s", o._statusCode, payload)
}

func (o *GetDataPointMappingsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetDataPointMappingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
