// Code generated by go-swagger; DO NOT EDIT.

package mappings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/mindconnect/v3/models"
)

// NewPostDataPointMappingsParams creates a new PostDataPointMappingsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostDataPointMappingsParams() *PostDataPointMappingsParams {
	return &PostDataPointMappingsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostDataPointMappingsParamsWithTimeout creates a new PostDataPointMappingsParams object
// with the ability to set a timeout on a request.
func NewPostDataPointMappingsParamsWithTimeout(timeout time.Duration) *PostDataPointMappingsParams {
	return &PostDataPointMappingsParams{
		timeout: timeout,
	}
}

// NewPostDataPointMappingsParamsWithContext creates a new PostDataPointMappingsParams object
// with the ability to set a context for a request.
func NewPostDataPointMappingsParamsWithContext(ctx context.Context) *PostDataPointMappingsParams {
	return &PostDataPointMappingsParams{
		Context: ctx,
	}
}

// NewPostDataPointMappingsParamsWithHTTPClient creates a new PostDataPointMappingsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostDataPointMappingsParamsWithHTTPClient(client *http.Client) *PostDataPointMappingsParams {
	return &PostDataPointMappingsParams{
		HTTPClient: client,
	}
}

/*
PostDataPointMappingsParams contains all the parameters to send to the API endpoint

	for the post data point mappings operation.

	Typically these are written to a http.Request.
*/
type PostDataPointMappingsParams struct {

	/* Mapping.

	   Object describing new mapping resource.
	*/
	Mapping *models.Mapping

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post data point mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDataPointMappingsParams) WithDefaults() *PostDataPointMappingsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post data point mappings params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostDataPointMappingsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post data point mappings params
func (o *PostDataPointMappingsParams) WithTimeout(timeout time.Duration) *PostDataPointMappingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post data point mappings params
func (o *PostDataPointMappingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post data point mappings params
func (o *PostDataPointMappingsParams) WithContext(ctx context.Context) *PostDataPointMappingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post data point mappings params
func (o *PostDataPointMappingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post data point mappings params
func (o *PostDataPointMappingsParams) WithHTTPClient(client *http.Client) *PostDataPointMappingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post data point mappings params
func (o *PostDataPointMappingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMapping adds the mapping to the post data point mappings params
func (o *PostDataPointMappingsParams) WithMapping(mapping *models.Mapping) *PostDataPointMappingsParams {
	o.SetMapping(mapping)
	return o
}

// SetMapping adds the mapping to the post data point mappings params
func (o *PostDataPointMappingsParams) SetMapping(mapping *models.Mapping) {
	o.Mapping = mapping
}

// WriteToRequest writes these params to a swagger request
func (o *PostDataPointMappingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Mapping != nil {
		if err := r.SetBodyParam(o.Mapping); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
