// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIRateLimitExceeded API rate limit exceeded
//
// swagger:model APIRateLimitExceeded
type APIRateLimitExceeded struct {

	// id
	ID string `json:"id,omitempty"`

	// message
	// Example: API rate limit exceeded.
	Message string `json:"message,omitempty"`
}

// Validate validates this API rate limit exceeded
func (m *APIRateLimitExceeded) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API rate limit exceeded based on context it is used
func (m *APIRateLimitExceeded) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIRateLimitExceeded) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRateLimitExceeded) UnmarshalBinary(b []byte) error {
	var res APIRateLimitExceeded
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
