// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/agentmanagement/v3/models"
)

// DeleteAgentsIDReader is a Reader for the DeleteAgentsID structure.
type DeleteAgentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAgentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAgentsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAgentsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAgentsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAgentsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAgentsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewDeleteAgentsIDPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteAgentsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAgentsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteAgentsIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAgentsIDNoContent creates a DeleteAgentsIDNoContent with default headers values
func NewDeleteAgentsIDNoContent() *DeleteAgentsIDNoContent {
	return &DeleteAgentsIDNoContent{}
}

/*
DeleteAgentsIDNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteAgentsIDNoContent struct {
}

// IsSuccess returns true when this delete agents Id no content response has a 2xx status code
func (o *DeleteAgentsIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete agents Id no content response has a 3xx status code
func (o *DeleteAgentsIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id no content response has a 4xx status code
func (o *DeleteAgentsIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete agents Id no content response has a 5xx status code
func (o *DeleteAgentsIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id no content response a status code equal to that given
func (o *DeleteAgentsIDNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete agents Id no content response
func (o *DeleteAgentsIDNoContent) Code() int {
	return 204
}

func (o *DeleteAgentsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdNoContent", 204)
}

func (o *DeleteAgentsIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdNoContent", 204)
}

func (o *DeleteAgentsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAgentsIDBadRequest creates a DeleteAgentsIDBadRequest with default headers values
func NewDeleteAgentsIDBadRequest() *DeleteAgentsIDBadRequest {
	return &DeleteAgentsIDBadRequest{}
}

/*
DeleteAgentsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteAgentsIDBadRequest struct {
	Payload *models.Badrequest
}

// IsSuccess returns true when this delete agents Id bad request response has a 2xx status code
func (o *DeleteAgentsIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id bad request response has a 3xx status code
func (o *DeleteAgentsIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id bad request response has a 4xx status code
func (o *DeleteAgentsIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete agents Id bad request response has a 5xx status code
func (o *DeleteAgentsIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id bad request response a status code equal to that given
func (o *DeleteAgentsIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete agents Id bad request response
func (o *DeleteAgentsIDBadRequest) Code() int {
	return 400
}

func (o *DeleteAgentsIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdBadRequest %s", 400, payload)
}

func (o *DeleteAgentsIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdBadRequest %s", 400, payload)
}

func (o *DeleteAgentsIDBadRequest) GetPayload() *models.Badrequest {
	return o.Payload
}

func (o *DeleteAgentsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Badrequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDUnauthorized creates a DeleteAgentsIDUnauthorized with default headers values
func NewDeleteAgentsIDUnauthorized() *DeleteAgentsIDUnauthorized {
	return &DeleteAgentsIDUnauthorized{}
}

/*
DeleteAgentsIDUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteAgentsIDUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this delete agents Id unauthorized response has a 2xx status code
func (o *DeleteAgentsIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id unauthorized response has a 3xx status code
func (o *DeleteAgentsIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id unauthorized response has a 4xx status code
func (o *DeleteAgentsIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete agents Id unauthorized response has a 5xx status code
func (o *DeleteAgentsIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id unauthorized response a status code equal to that given
func (o *DeleteAgentsIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete agents Id unauthorized response
func (o *DeleteAgentsIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteAgentsIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdUnauthorized %s", 401, payload)
}

func (o *DeleteAgentsIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdUnauthorized %s", 401, payload)
}

func (o *DeleteAgentsIDUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *DeleteAgentsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDForbidden creates a DeleteAgentsIDForbidden with default headers values
func NewDeleteAgentsIDForbidden() *DeleteAgentsIDForbidden {
	return &DeleteAgentsIDForbidden{}
}

/*
DeleteAgentsIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteAgentsIDForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this delete agents Id forbidden response has a 2xx status code
func (o *DeleteAgentsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id forbidden response has a 3xx status code
func (o *DeleteAgentsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id forbidden response has a 4xx status code
func (o *DeleteAgentsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete agents Id forbidden response has a 5xx status code
func (o *DeleteAgentsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id forbidden response a status code equal to that given
func (o *DeleteAgentsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete agents Id forbidden response
func (o *DeleteAgentsIDForbidden) Code() int {
	return 403
}

func (o *DeleteAgentsIDForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdForbidden %s", 403, payload)
}

func (o *DeleteAgentsIDForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdForbidden %s", 403, payload)
}

func (o *DeleteAgentsIDForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *DeleteAgentsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDNotFound creates a DeleteAgentsIDNotFound with default headers values
func NewDeleteAgentsIDNotFound() *DeleteAgentsIDNotFound {
	return &DeleteAgentsIDNotFound{}
}

/*
DeleteAgentsIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAgentsIDNotFound struct {
	Payload *models.Notfound
}

// IsSuccess returns true when this delete agents Id not found response has a 2xx status code
func (o *DeleteAgentsIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id not found response has a 3xx status code
func (o *DeleteAgentsIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id not found response has a 4xx status code
func (o *DeleteAgentsIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete agents Id not found response has a 5xx status code
func (o *DeleteAgentsIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id not found response a status code equal to that given
func (o *DeleteAgentsIDNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete agents Id not found response
func (o *DeleteAgentsIDNotFound) Code() int {
	return 404
}

func (o *DeleteAgentsIDNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdNotFound %s", 404, payload)
}

func (o *DeleteAgentsIDNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdNotFound %s", 404, payload)
}

func (o *DeleteAgentsIDNotFound) GetPayload() *models.Notfound {
	return o.Payload
}

func (o *DeleteAgentsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Notfound)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDPreconditionFailed creates a DeleteAgentsIDPreconditionFailed with default headers values
func NewDeleteAgentsIDPreconditionFailed() *DeleteAgentsIDPreconditionFailed {
	return &DeleteAgentsIDPreconditionFailed{}
}

/*
DeleteAgentsIDPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type DeleteAgentsIDPreconditionFailed struct {
	Payload *models.Preconditionfailed
}

// IsSuccess returns true when this delete agents Id precondition failed response has a 2xx status code
func (o *DeleteAgentsIDPreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id precondition failed response has a 3xx status code
func (o *DeleteAgentsIDPreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id precondition failed response has a 4xx status code
func (o *DeleteAgentsIDPreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete agents Id precondition failed response has a 5xx status code
func (o *DeleteAgentsIDPreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id precondition failed response a status code equal to that given
func (o *DeleteAgentsIDPreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the delete agents Id precondition failed response
func (o *DeleteAgentsIDPreconditionFailed) Code() int {
	return 412
}

func (o *DeleteAgentsIDPreconditionFailed) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdPreconditionFailed %s", 412, payload)
}

func (o *DeleteAgentsIDPreconditionFailed) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdPreconditionFailed %s", 412, payload)
}

func (o *DeleteAgentsIDPreconditionFailed) GetPayload() *models.Preconditionfailed {
	return o.Payload
}

func (o *DeleteAgentsIDPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Preconditionfailed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDTooManyRequests creates a DeleteAgentsIDTooManyRequests with default headers values
func NewDeleteAgentsIDTooManyRequests() *DeleteAgentsIDTooManyRequests {
	return &DeleteAgentsIDTooManyRequests{}
}

/*
DeleteAgentsIDTooManyRequests describes a response with status code 429, with default header values.

API rate limit exceeded.
*/
type DeleteAgentsIDTooManyRequests struct {
	Payload *models.APIRateLimitExceeded
}

// IsSuccess returns true when this delete agents Id too many requests response has a 2xx status code
func (o *DeleteAgentsIDTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id too many requests response has a 3xx status code
func (o *DeleteAgentsIDTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id too many requests response has a 4xx status code
func (o *DeleteAgentsIDTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete agents Id too many requests response has a 5xx status code
func (o *DeleteAgentsIDTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this delete agents Id too many requests response a status code equal to that given
func (o *DeleteAgentsIDTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the delete agents Id too many requests response
func (o *DeleteAgentsIDTooManyRequests) Code() int {
	return 429
}

func (o *DeleteAgentsIDTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdTooManyRequests %s", 429, payload)
}

func (o *DeleteAgentsIDTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdTooManyRequests %s", 429, payload)
}

func (o *DeleteAgentsIDTooManyRequests) GetPayload() *models.APIRateLimitExceeded {
	return o.Payload
}

func (o *DeleteAgentsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRateLimitExceeded)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDInternalServerError creates a DeleteAgentsIDInternalServerError with default headers values
func NewDeleteAgentsIDInternalServerError() *DeleteAgentsIDInternalServerError {
	return &DeleteAgentsIDInternalServerError{}
}

/*
DeleteAgentsIDInternalServerError describes a response with status code 500, with default header values.

unexpected error
*/
type DeleteAgentsIDInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this delete agents Id internal server error response has a 2xx status code
func (o *DeleteAgentsIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete agents Id internal server error response has a 3xx status code
func (o *DeleteAgentsIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete agents Id internal server error response has a 4xx status code
func (o *DeleteAgentsIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete agents Id internal server error response has a 5xx status code
func (o *DeleteAgentsIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete agents Id internal server error response a status code equal to that given
func (o *DeleteAgentsIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete agents Id internal server error response
func (o *DeleteAgentsIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteAgentsIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdInternalServerError %s", 500, payload)
}

func (o *DeleteAgentsIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /agents/{id}][%d] deleteAgentsIdInternalServerError %s", 500, payload)
}

func (o *DeleteAgentsIDInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteAgentsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAgentsIDDefault creates a DeleteAgentsIDDefault with default headers values
func NewDeleteAgentsIDDefault(code int) *DeleteAgentsIDDefault {
	return &DeleteAgentsIDDefault{
		_statusCode: code,
	}
}

/*
DeleteAgentsIDDefault describes a response with status code -1, with default header values.

Other error with any status code and response body format.
*/
type DeleteAgentsIDDefault struct {
	_statusCode int
}

// IsSuccess returns true when this delete agents ID default response has a 2xx status code
func (o *DeleteAgentsIDDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete agents ID default response has a 3xx status code
func (o *DeleteAgentsIDDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete agents ID default response has a 4xx status code
func (o *DeleteAgentsIDDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete agents ID default response has a 5xx status code
func (o *DeleteAgentsIDDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete agents ID default response a status code equal to that given
func (o *DeleteAgentsIDDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the delete agents ID default response
func (o *DeleteAgentsIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAgentsIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /agents/{id}][%d] DeleteAgentsID default", o._statusCode)
}

func (o *DeleteAgentsIDDefault) String() string {
	return fmt.Sprintf("[DELETE /agents/{id}][%d] DeleteAgentsID default", o._statusCode)
}

func (o *DeleteAgentsIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
