// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/agentmanagement/v3/models"
)

// GetAgentsReader is a Reader for the GetAgents structure.
type GetAgentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAgentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAgentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAgentsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetAgentsTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAgentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetAgentsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAgentsOK creates a GetAgentsOK with default headers values
func NewGetAgentsOK() *GetAgentsOK {
	return &GetAgentsOK{}
}

/*
GetAgentsOK describes a response with status code 200, with default header values.

Array of agents
*/
type GetAgentsOK struct {
	Payload *models.PagedAgent
}

// IsSuccess returns true when this get agents o k response has a 2xx status code
func (o *GetAgentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get agents o k response has a 3xx status code
func (o *GetAgentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents o k response has a 4xx status code
func (o *GetAgentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agents o k response has a 5xx status code
func (o *GetAgentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents o k response a status code equal to that given
func (o *GetAgentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get agents o k response
func (o *GetAgentsOK) Code() int {
	return 200
}

func (o *GetAgentsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsOK %s", 200, payload)
}

func (o *GetAgentsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsOK %s", 200, payload)
}

func (o *GetAgentsOK) GetPayload() *models.PagedAgent {
	return o.Payload
}

func (o *GetAgentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PagedAgent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsBadRequest creates a GetAgentsBadRequest with default headers values
func NewGetAgentsBadRequest() *GetAgentsBadRequest {
	return &GetAgentsBadRequest{}
}

/*
GetAgentsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAgentsBadRequest struct {
	Payload *models.Badrequest
}

// IsSuccess returns true when this get agents bad request response has a 2xx status code
func (o *GetAgentsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents bad request response has a 3xx status code
func (o *GetAgentsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents bad request response has a 4xx status code
func (o *GetAgentsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents bad request response has a 5xx status code
func (o *GetAgentsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents bad request response a status code equal to that given
func (o *GetAgentsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get agents bad request response
func (o *GetAgentsBadRequest) Code() int {
	return 400
}

func (o *GetAgentsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsBadRequest %s", 400, payload)
}

func (o *GetAgentsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsBadRequest %s", 400, payload)
}

func (o *GetAgentsBadRequest) GetPayload() *models.Badrequest {
	return o.Payload
}

func (o *GetAgentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Badrequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsUnauthorized creates a GetAgentsUnauthorized with default headers values
func NewGetAgentsUnauthorized() *GetAgentsUnauthorized {
	return &GetAgentsUnauthorized{}
}

/*
GetAgentsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAgentsUnauthorized struct {
	Payload *models.Unauthorized
}

// IsSuccess returns true when this get agents unauthorized response has a 2xx status code
func (o *GetAgentsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents unauthorized response has a 3xx status code
func (o *GetAgentsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents unauthorized response has a 4xx status code
func (o *GetAgentsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents unauthorized response has a 5xx status code
func (o *GetAgentsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents unauthorized response a status code equal to that given
func (o *GetAgentsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get agents unauthorized response
func (o *GetAgentsUnauthorized) Code() int {
	return 401
}

func (o *GetAgentsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsUnauthorized %s", 401, payload)
}

func (o *GetAgentsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsUnauthorized %s", 401, payload)
}

func (o *GetAgentsUnauthorized) GetPayload() *models.Unauthorized {
	return o.Payload
}

func (o *GetAgentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Unauthorized)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsForbidden creates a GetAgentsForbidden with default headers values
func NewGetAgentsForbidden() *GetAgentsForbidden {
	return &GetAgentsForbidden{}
}

/*
GetAgentsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAgentsForbidden struct {
	Payload *models.Forbidden
}

// IsSuccess returns true when this get agents forbidden response has a 2xx status code
func (o *GetAgentsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents forbidden response has a 3xx status code
func (o *GetAgentsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents forbidden response has a 4xx status code
func (o *GetAgentsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents forbidden response has a 5xx status code
func (o *GetAgentsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents forbidden response a status code equal to that given
func (o *GetAgentsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get agents forbidden response
func (o *GetAgentsForbidden) Code() int {
	return 403
}

func (o *GetAgentsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsForbidden %s", 403, payload)
}

func (o *GetAgentsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsForbidden %s", 403, payload)
}

func (o *GetAgentsForbidden) GetPayload() *models.Forbidden {
	return o.Payload
}

func (o *GetAgentsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Forbidden)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsTooManyRequests creates a GetAgentsTooManyRequests with default headers values
func NewGetAgentsTooManyRequests() *GetAgentsTooManyRequests {
	return &GetAgentsTooManyRequests{}
}

/*
GetAgentsTooManyRequests describes a response with status code 429, with default header values.

API rate limit exceeded.
*/
type GetAgentsTooManyRequests struct {
	Payload *models.APIRateLimitExceeded
}

// IsSuccess returns true when this get agents too many requests response has a 2xx status code
func (o *GetAgentsTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents too many requests response has a 3xx status code
func (o *GetAgentsTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents too many requests response has a 4xx status code
func (o *GetAgentsTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get agents too many requests response has a 5xx status code
func (o *GetAgentsTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get agents too many requests response a status code equal to that given
func (o *GetAgentsTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get agents too many requests response
func (o *GetAgentsTooManyRequests) Code() int {
	return 429
}

func (o *GetAgentsTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsTooManyRequests %s", 429, payload)
}

func (o *GetAgentsTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsTooManyRequests %s", 429, payload)
}

func (o *GetAgentsTooManyRequests) GetPayload() *models.APIRateLimitExceeded {
	return o.Payload
}

func (o *GetAgentsTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIRateLimitExceeded)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsInternalServerError creates a GetAgentsInternalServerError with default headers values
func NewGetAgentsInternalServerError() *GetAgentsInternalServerError {
	return &GetAgentsInternalServerError{}
}

/*
GetAgentsInternalServerError describes a response with status code 500, with default header values.

unexpected error
*/
type GetAgentsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get agents internal server error response has a 2xx status code
func (o *GetAgentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get agents internal server error response has a 3xx status code
func (o *GetAgentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get agents internal server error response has a 4xx status code
func (o *GetAgentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get agents internal server error response has a 5xx status code
func (o *GetAgentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get agents internal server error response a status code equal to that given
func (o *GetAgentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get agents internal server error response
func (o *GetAgentsInternalServerError) Code() int {
	return 500
}

func (o *GetAgentsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsInternalServerError %s", 500, payload)
}

func (o *GetAgentsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /agents][%d] getAgentsInternalServerError %s", 500, payload)
}

func (o *GetAgentsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentsDefault creates a GetAgentsDefault with default headers values
func NewGetAgentsDefault(code int) *GetAgentsDefault {
	return &GetAgentsDefault{
		_statusCode: code,
	}
}

/*
GetAgentsDefault describes a response with status code -1, with default header values.

Other error with any status code and response body format.
*/
type GetAgentsDefault struct {
	_statusCode int
}

// IsSuccess returns true when this get agents default response has a 2xx status code
func (o *GetAgentsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this get agents default response has a 3xx status code
func (o *GetAgentsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this get agents default response has a 4xx status code
func (o *GetAgentsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this get agents default response has a 5xx status code
func (o *GetAgentsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this get agents default response a status code equal to that given
func (o *GetAgentsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the get agents default response
func (o *GetAgentsDefault) Code() int {
	return o._statusCode
}

func (o *GetAgentsDefault) Error() string {
	return fmt.Sprintf("[GET /agents][%d] GetAgents default", o._statusCode)
}

func (o *GetAgentsDefault) String() string {
	return fmt.Sprintf("[GET /agents][%d] GetAgents default", o._statusCode)
}

func (o *GetAgentsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
