// Code generated by go-swagger; DO NOT EDIT.

package agent_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/calacaly/mindconnect-go/internal/api/agentmanagement/v3/models"
)

// NewPostAgentsParams creates a new PostAgentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAgentsParams() *PostAgentsParams {
	return &PostAgentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAgentsParamsWithTimeout creates a new PostAgentsParams object
// with the ability to set a timeout on a request.
func NewPostAgentsParamsWithTimeout(timeout time.Duration) *PostAgentsParams {
	return &PostAgentsParams{
		timeout: timeout,
	}
}

// NewPostAgentsParamsWithContext creates a new PostAgentsParams object
// with the ability to set a context for a request.
func NewPostAgentsParamsWithContext(ctx context.Context) *PostAgentsParams {
	return &PostAgentsParams{
		Context: ctx,
	}
}

// NewPostAgentsParamsWithHTTPClient creates a new PostAgentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAgentsParamsWithHTTPClient(client *http.Client) *PostAgentsParams {
	return &PostAgentsParams{
		HTTPClient: client,
	}
}

/*
PostAgentsParams contains all the parameters to send to the API endpoint

	for the post agents operation.

	Typically these are written to a http.Request.
*/
type PostAgentsParams struct {

	/* Agent.

	   Object describing new agent resource.
	*/
	Agent *models.CreateAgentRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post agents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAgentsParams) WithDefaults() *PostAgentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post agents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAgentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post agents params
func (o *PostAgentsParams) WithTimeout(timeout time.Duration) *PostAgentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post agents params
func (o *PostAgentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post agents params
func (o *PostAgentsParams) WithContext(ctx context.Context) *PostAgentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post agents params
func (o *PostAgentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post agents params
func (o *PostAgentsParams) WithHTTPClient(client *http.Client) *PostAgentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post agents params
func (o *PostAgentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgent adds the agent to the post agents params
func (o *PostAgentsParams) WithAgent(agent *models.CreateAgentRequest) *PostAgentsParams {
	o.SetAgent(agent)
	return o
}

// SetAgent adds the agent to the post agents params
func (o *PostAgentsParams) SetAgent(agent *models.CreateAgentRequest) {
	o.Agent = agent
}

// WriteToRequest writes these params to a swagger request
func (o *PostAgentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Agent != nil {
		if err := r.SetBodyParam(o.Agent); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
